apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: full-stack-chatapp
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29hZG1pbg==
  MONGO_INITDB_ROOT_PASSWORD: c2VjcmV0
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleQ==
